version: '3'
services:
  backend:
    container_name: 'backend'
    restart: unless-stopped
    build: .
    ports:
      - 80:8080
    working_dir: '/root/src'
    tty: true
    volumes:
      - ./src:/root/src
    command: sh -c 'python main.py'